### ISSUE TITLE
需求：实现读取API数据保存成JSON文件

### ISSUE THREAD

**Issue by fushang318** [fushang318/sibbay_icp_cert#1]
需求如下：
1. 读取 https://api.github.com/repos/sibbay-ai/public
2. 保存成JSON文件

**Comment by fushang318** [comment]
@ben7th 
这是需求的ISSUE

**Comment by fushang318** [comment]
@ben7th   
我申请开发 Size：0.1 Deadline：2017-12-17

**Comment by ben7th** [comment]
pr 已合并，此 issue 关闭
