### ISSUE TITLE
现针对 ICP 理解工作发起协作

### ISSUE THREAD

**Issue by fushang318** [fushang318/sibbay_icp_cert#10]
里程碑

贡献者认证流程

参与者

@ben7th mentor
@fushang318 贡献者

文档

https://github.com/sibbay-ai/public

相关 issue

https://github.com/fushang318/sibbay_icp_cert/issues/9

工作目标

 目标一：明确一下奖励发放机制
 目标二：明确一下工作量统计
 目标三：一个后端ISSUE，如果PR合并并关闭了这个ISSUE，但是联调又发现了BUG，那么要重新发起一个单独计算 icp size 的BUG ISSUE

**Comment by ben7th** [comment]
@fushang318 已对原 issue 进行回复。
请列出 public 的相关规范文档到这个协作 issue

**Comment by fushang318** [comment]
@ben7th 
文档是：
https://github.com/sibbay-ai/public/blob/master/ICP%20%E5%A5%96%E5%8A%B1%E6%9C%BA%E5%88%B6.md

https://github.com/sibbay-ai/public/blob/master/issue%20%E8%A7%84%E8%8C%83.md

**Comment by fushang318** [comment]
@ben7th 
codeclimate 如何设置啊，我这里提交PR以后，没有触发 codeclimate

**Comment by ben7th** [comment]
@fushang318 
访问 https://codeclimate.com/ 添加工程
pr 指向哪个分支，就需要在 codeclimate 里把哪个分支设为主分支
这样才会触发检查

**Comment by fushang318** [comment]
PR:
1. https://github.com/fushang318/sibbay_icp_cert/pull/8
2. https://github.com/fushang318/sibbay_icp_cert/pull/6

**Comment by ben7th** [comment]
流程已结束，此 issue 关闭
