### ISSUE TITLE
icp理解测试

### ISSUE THREAD

**Issue by fushang318** [fushang318/sibbay_icp_cert#9]
@ben7th 你提问我问题吧

**Comment by ben7th** [comment]
问题：

- 贡献者工作量的认可，唯一标准是什么？
- pr 要指向什么分支？
- 贡献者费用如何发放？

**Comment by fushang318** [comment]
> 贡献者工作量的认可，唯一标准是什么？

贡献者执行标记 ICP标签的 ISSUE 任务，然后ISSUE被 close 掉
这些ISSUE标记了 size ，size 的总和就是工作量

**Comment by fushang318** [comment]
> pr 要指向什么分支？

develop 分支

**Comment by fushang318** [comment]
> 贡献者费用如何发放？

每月15日为节点，通过码市结算

**Comment by ben7th** [comment]
@fushang318
如果执行过程出现意外情况，导致 issue 被 close，是没有工作量认可的。
所以 issue 的 close 不是工作量认可的唯一标准。

**Comment by fushang318** [comment]
> 如果执行过程出现意外情况，导致 issue 被 close，是没有工作量认可的。
> 所以 issue 的 close 不是工作量认可的唯一标准。

哦哦，抱歉，我对 ISSUE 的 close  情况没有注意到意外情况下的 close 
我补充一下，回答
ICP ISSUE 被开发者正常申请到以后，正常的完成了开发工作，包括按照流程进行了 commIt 和 PR，并且 pr 被合并到了 develop ，然后 issue 被 commiter 正常关闭

**Comment by ben7th** [comment]
沟通完毕，此 issue 关闭
